Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/xingyu/secure-robust-federated-learning/src/simulate.py", line 172, in <module>
    network = ConvNet(input_size=32, input_channel=3, classes=10, filters1=30, filters2=30, fc_size=200).to(device)
  File "/home/xingyu/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/xingyu/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/xingyu/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/xingyu/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

